// PHP Syntax Explanation

// PHP scripts start with <?php and end with ?>
// PHP statements end with a semicolon (;)
// PHP is case-sensitive for variables but not for function names

// Example 1: Basic PHP Script
<?php
// This will output text to the browser
echo "Hello, World!";
?>

// Example 2: PHP inside HTML
<!DOCTYPE html>
<html>
<head>
    <title>PHP in HTML Example</title>
</head>
<body>
    <h1>Welcome to My Website</h1>
    <?php
    // Embedding PHP in HTML
    echo "<p>This is a paragraph generated by PHP.</p>";
    ?>
</body>
</html>